### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib

### ISSUE THREAD

**Issue by Jennifer88huang-zz** [Jennifer88huang/issues#1]
**Issue**

```
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
Abort trap: 6
```

**Solution**
```
brew install rbenv/tap/openssl@1.0
ln -sfn /usr/local/Cellar/openssl@1.0/1.0.2t /usr/local/opt/openssl
```

**System**
MacOS Big Blur 11.3.1

reference: 
- https://stackoverflow.com/questions/59006602/dyld-library-not-loaded-usr-local-opt-openssl-lib-libssl-1-0-0-dylib
- https://github.com/kelaberetiv/TagUI/issues/86

**Comment by kadnan** [comment]
Will it work for Catalina?
